create table public.dash_pedidos_local (
  "PDOC_UUID" bigint generated by default as identity not null,
  "PDOC_PK" bigint not null,
  "CEMP_PK" bigint not null,
  "PDOC_DT_EMISSAO" date null,
  "PDOC_VLR_TOTAL" numeric(14, 2) null,
  "CCOT_VEND_PK" bigint null,
  "PDOC_HR_EMISSAO" time without time zone null,
  constraint dash_pedidos_local_pkey primary key ("PDOC_UUID")
) TABLESPACE pg_default;

create table public.dash_itens_pedido_local (
  "PDOC_UUID" bigint not null,
  "PITEN_PK" bigint not null,
  "PDOC_PK" bigint not null,
  "EPRO_PK" bigint not null,
  "PITEN_QTD" real null,
  "PITEN_VLR_UNITARIO" numeric(14, 2) null,
  "PITEN_VLR_TOT_BRUTO" numeric(14, 2) null,
  "PITEN_VLR_TOT_LIQUIDO" numeric(14, 2) null,
  "PITEN_VLR_DESCONTO" numeric(14, 2) null,
  "PITEN_VLR_ACRESCIMO" numeric(14, 2) null,
  constraint dash_itens_pedido_local_PDOC_PK_fkey foreign KEY ("PDOC_PK") references dash_produtos_local ("EPRO_PK"),
  constraint dash_itens_pedido_local_PDOC_UUID_fkey foreign KEY ("PDOC_UUID") references dash_pedidos_local ("PDOC_UUID")
) TABLESPACE pg_default;
