create table public.pedidos_local (
  "PDOC_UUID" bigint generated by default as identity not null,
  "PDOC_PK" bigint not null,
  "CEMP_PK" bigint not null,
  "PDOC_DT_EMISSAO" date null,
  "PDOC_VLR_TOTAL" numeric(14, 2) null,
  "CCOT_VEND_PK" bigint null,
  "PDOC_HR_EMISSAO" time without time zone null,
  constraint pedidos_local_pkey primary key ("PDOC_UUID")
) TABLESPACE pg_default;

create table public.intes_pedido_local (
  "PDOC_UUID" bigint not null,
  "PITEN_PK" bigint not null,
  "PDOC_PK" bigint not null,
  "EPRO_PK" bigint not null,
  "PITEN_QTD" real null,
  "PITEN_VLR_UNITARIO" numeric(14, 2) null,
  "PITEN_VLR_TOTAL" numeric(14, 2) null,
  constraint intes_pedido_local_PDOC_PK_fkey foreign KEY ("PDOC_PK") references produtos_local ("EPRO_PK"),
  constraint intes_pedido_local_PDOC_UUID_fkey foreign KEY ("PDOC_UUID") references pedidos_local ("PDOC_UUID")
) TABLESPACE pg_default;
